name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build static API
        run: npm run build

      - name: Upload built files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
